### PR TITLE
Update spotlight dependency and use new spotlight root path

### PR DESCRIPTION
**Pull request by cbeer**
This should be sufficiently backwards-compatible for our purposes. All our applications only contain a single exhibit, so we'll trigger the `spotlight/exhibits#index` redirect behavior, mimicking existing behavior.

### CODE REVIEW

**Comment by ndushay** [comment]
Are all the gem updates tied directly to the spotlight gem update?  If not, perhaps separate commits?  o.w. looks fine to me.

**Comment by cbeer** [comment]
Sure, that makes sense. Those were only blacklight-spotlight dependencies, so let me `bundle update` everything.

**Comment by ndushay** [comment]
uh oh - some gem update made it unhappy.  :cry:

**Comment by cbeer** [comment]
Ah, I forgot about @jkeck's changes that got released in spotlight 0.8.1.

**Comment by cbeer** [comment]
@ndushay :cry: => :smile:

**Pull request merged**
