### PR TITLE
Adjust font sizes for various headings

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by ggeisler** [comment]
Can you provide screenshots so I can see what the changes look like?

**Comment by cbeer** [comment]
I was afraid somebody would ask for that. Guess I need to get some collections going locally..

**Comment by ggeisler** [comment]
Well, I'm sure the changes are good. We could merge them and if I think something needs adjusting we can deal with that in another commit.

**Comment by cbeer** [comment]
:+1: I think these were the major changes we discussed, and there will probably be others.

**Pull request merged**
